#ifdef CH_LANG_CC
/*
 *      _______              __
 *     / ___/ /  ___  __ _  / /  ___
 *    / /__/ _ \/ _ \/  V \/ _ \/ _ \
 *    \___/_//_/\___/_/_/_/_.__/\___/
 *    Please refer to Copyright.txt, in Chombo's root directory.
 */
#endif

//  ANAG, LBNL

///meant to be overridden at compile time if necessary
#ifndef _CH_EBIS_ORDER_H_
#define _CH_EBIS_ORDER_H_


/// maximum order of moment used in calc
/**
   this can be overridden at compile time (compile time of the LIBRARY!!!)
*/
#define CH_EBIS_ORDER  2




#endif
