
ebase = Multigrid

# the location of the Chombo "lib" directory
CHOMBO_HOME = ../../../../lib

# names of Chombo libraries needed by this program, in order of search.
LibNames = BoxTools

# the locations of the source code directories
base_dir = .
src_dirs = ../src


# input file for 'run' target
INPUT = regression.inputs
# shared code for building example programs
include $(CHOMBO_HOME)/mk/Make.example

# application-specific variables

# application-specific targets
