#!/bin/sh

debug="--enable-opt"
install_dir=$PWD/lib/cab-mpicc-gfortran-opt

cd src
./configure $debug \
            CC=mpicc \
            CFLAGS="-O3 " \
            CXX=mpicxx \
            CXXFLAGS="-O3 " \
            F77=mpif77 \
            F77FLAGS="-O3 " \
            --prefix=$install_dir
cd ..

