#!/bin/sh

debug="--enable-opt"

install_dir=$PWD/lib/ANAG-mpicc-gfortran-opt

cd src
./configure $debug \
            --with-CC=/usr/bin/mpicc \
            --with-CFLAGS="-O2 " \
            --with-CXX=/usr/bin/mpiCC \
            --with-CXXFLAGS="-g -O2 " \
            --with-F77=/usr/bin/mpif77 \
            --with-F77FLAGS="-g -O2 " \
            --prefix=$install_dir
cd ..

