#!/bin/sh

debug="--enable-debug"
if test "dbg" = "opt"; then
   debug="--enable-opt";
fi

mpi_include=`echo '-I/usr/local/tools/mvapich-intel/include' | sed 's/-I//g'`

install_dir=$PWD/lib/atlas-mpiicpc-ifort-dbg

cd src
./configure $debug \
            --with-CC=/usr/local/bin/mpiicc \
            --with-CFLAGS="-g " \
            --with-CXX=/usr/local/bin/mpiicpc \
            --with-CXXFLAGS="-g " \
            --with-F77=/usr/local/tools/ifort-9.1.052/bin/ifort \
            --with-F77FLAGS="-g " \
            --with-MPI-include="$mpi_include" \
            --prefix=$install_dir
cd ..

