#ifdef CH_LANG_CC
/*
*      _______              __
*     / ___/ /  ___  __ _  / /  ___
*    / /__/ _ \/ _ \/  V \/ _ \/ _ \
*    \___/_//_/\___/_/_/_/_.__/\___/
*    Please refer to Copyright.txt, in Chombo's root directory.
*/
#endif

#ifndef _NORMALDERIVATIVENEWIMPLEM_H_
#define _NORMALDERIVATIVENEWIMPLEM_H_

#include "NamespaceHeader.H"

// Null constructor
template <int dim> NormalDerivativeNew<dim>::NormalDerivativeNew()
{
}

// Destructor
template <int dim> NormalDerivativeNew<dim>::~NormalDerivativeNew()
{
}


#include "NamespaceFooter.H"

#endif
