


# the base name(s) of the application(s) in this directory
ebase = smoothnDemo

# the location of Chombo lib dir
CHOMBO_HOME = ../../../../../Chombo/lib

# names of Chombo libraries needed by this program, in order of search.
 LibNames = AMRTools BoxTools

# relative paths to source code directories
base_dir  = .
src_dirs  = 

# shared code for building example programs
include $(CHOMBO_HOME)/mk/Make.example

# application-specific variables
XTRALIBFLAGS = -lfftw3

# application-specific targets
