


# the base name(s) of the application(s) in this directory
ebase = newBdInit

# the location of Chombo lib dir
CHOMBO_HOME = ../../../Chombo/lib

# names of Chombo libraries needed by this program, in order of search.
 LibNames = AMRTools BoxTools 

# relative paths to source code directories
base_dir  = .
src_dirs  = ../src

# shared code for building example programs
include $(CHOMBO_HOME)/mk/Make.example

# application-specific variables

# application-specific targets
