#!/bin/sh

file_name=$(basename $0)
config_name=$(echo ${file_name} | sed s/^doconfig-//)
base_dir=$(dirname $0)
base_dir=$(cd ${base_dir}; pwd)
install_dir=${base_dir}/lib/${config_name}

echo "Compiling with the following compilers:"
echo "CC=$MPICC"
echo "CXX=$MPICXX"
echo "F77=$MPIF77"

cd ${base_dir}/src
./configure "--enable-opt" --prefix=$install_dir \
            CC=${MPICC} \
            CXX=${MPICXX} \
            F77=${MPIF77}

